name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
    env:
      RAILS_ENV: test
      RACK_ENV: test

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Cache bundle
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ env.ACTION_CACHE_VERSION }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-${{ env.ACTION_CACHE_VERSION }}-
    - name: Install dependencies
      run: |
        sudo apt-get install libmariadb-dev
        bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
    - name: Configure
      run: |
        cp config/config.sample.yml config/config.yml
        echo 'test:
          adapter: mysql2
          database: sentinel_test
          username: root
          password: root
          host: localhost
          port: ${{ job.services.mysql.ports['3306'] }}
        ' > config/database.yml
    - name: Rubocop
      run: bundle exec rubocop
    - name: erblint
      run: bundle exec erblint --lint-all
    - name: Create database
      run: |
        sudo systemctl start mysql.service
        mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
        bundle exec rake db:create db:migrate db:seed --trace
